
POST http://localhost:4300/notebook
Content-Type: application/json

{
    "note_title":"learned node",
    "contentet":"created endpoints using express",
    "date_created":"2023-07-28"
}

###
GET http://localhost:4300/notebook

###
GET http://localhost:4300/notebook/244fcc13-d98b-4879-8d10-a35bcf082f01

###
PUT http://localhost:4300/notebook/244fcc13-d98b-4879-8d10-a35bcf082f01
Content-Type: application/json

{
    "note_title":"Dependencies",
    "contentet":"Installed and configured dependences using express",
    "date_created":"2023-07-28"
}

###
DELETE http://localhost:4300/notebook/3fe727fd-4dae-4e6a-9792-a13ff3eb9e7b
